### ISSUE TITLE
Выбираем с каким проектом будем работать

### ISSUE THREAD

**Issue by ale5000** [ale5000/iu73_23_24#1]
Предлагаю работать с библиотекой Boost C++ library collections:
Достоинства:
Много примеров;
Кросс-платформенность (Windows, MacOS, Linux);
Одна из самый популярных и старых библиотек в мире С++
Недостатки:
Требует умения настраивать её компиляцию, линковать ее к проекту

ImGui - библиотека для построения оконных приложений на C++
Достоинства:
Есть проекты под Visual Studio;
Используется в GameDev.

Ваши предложения?

**Comment by ComradeMashkov** [comment]
1. Armadillo - библиотека для работы с линейной алгеброй и матрицами.
Пример:
```C++
mat A(5, 10, fill::randu);
mat B(5, 10, fill::randu);
mat C(10, 5, fill::randu);
```
Имеет MATLAB-схожий синтаксис, кросс-платформенная! Подойдет управленцам которые не могут отвыкнуть от матлабчика

2. NumCpp - библиотека, переносящая питоновскую библиотеку NumPy на плюсы.
Пример (NumPy):
```Python
a = np.array([[1, 2], [3, 4], [5, 6]])
```
Пример (NumCpp):
```C++
nc::NdArray<int> a = { {1, 2}, {3, 4}, {5, 6} }
```
Имеет Python-схожий синтаксис для быстрого построение матриц, векторов и численных операций с ними, кросс-платформенная.

**Comment by ale5000** [comment]
Выбрали boost
